######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 4 15:58:33 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += serverWid.h \
    server.h \
    SSLServer.h
FORMS += serverWid.ui
SOURCES += main.cpp serverWid.cpp \
    server.cpp \
    SSLServer.cpp
QT += network
