######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 4 15:58:33 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += server.h serverWid.h sslserver.h
FORMS += serverWid.ui
SOURCES += main.cpp server.cpp serverWid.cpp sslserver.cpp
QT += network
